### ISSUE TITLE
update函数只输出keypoints

### ISSUE THREAD

**Issue by hammer422** [CalciferZh/Minimal-IK#12]
您好，minimal-IK是一个非常有启发的项目

[function](https://github.com/CalciferZh/Minimal-IK/blob/master/models.py#L97)
关于update函数我有个问题，我注意到优化的时候只有keypoints被用到，而verts没有被用到，同时要计算verts涉及到几个778size的运算。
请问如果为了速度，只输出keypoints，是否有可能略过verts的部分相关计算

谢谢！

**Comment by CalciferZh** [comment]
是的，verts的计算是可以完全避免的，在得到当前theta的估计值之后直接根据forward kinematics算keypoints位置就可以了

**Comment by hammer422** [comment]
谢谢！
