### ISSUE TITLE
How to visualize the .obj file?

### ISSUE THREAD

**Issue by SizheAn** [CalciferZh/Minimal-IK#13]
Hi,

I successfully ran the example.py and got gt.obj and est.obj. But I didn't see where I can visualize them.

After searching I found that I can visualize it use open3d, but when I load the .obj file it throw error:

```
import copy
import open3d as o3d

print("Testing mesh in open3d ...")
mesh = o3d.io.read_triangle_mesh("est.obj")
print(mesh)
```

It gives:
`
Testing mesh in open3d ...
Read geometry::TriangleMesh failed: unknown file extension.
`

Any suggestions? Thanks!

**Comment by SizheAn** [comment]
Also, I'm wondering if it is possible to reconstruct smpl model parameters when the human keypoint aren't the same format as the default one.  For example, I'm using a in-house dataset obtained keypoint coordinates from Kinect V2, which output 25 keypoints coordinates in 3D (https://lisajamhoury.medium.com/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16). These 25 keypoints are partially different from the 24 keypoints from SMPLArmature. 

Also, obviously, https://github.com/CalciferZh/Minimal-IK/blob/72bfcbb768355fcc6706ca8cbdf50c3da25f9f63/example.py#L35 the pca_pose here is the PCA component instead of the actual keypoint matrix. Where should I input the actual keypoint matrix?

Could you please give me some insight?

**Comment by CalciferZh** [comment]
You can use MeshLab to view obj files.

As for a different set of keypoints, you can manually specify the correspondence between these keypoints and mesh vertices, and perform a similar optimization to solve for the parameters that best align these mesh vertices to the detected keypoints. You may also refer to this repo: https://github.com/nghorbani/moshpp

**Comment by SizheAn** [comment]
> You can use MeshLab to view obj files.
> 
> As for a different set of keypoints, you can manually specify the correspondence between these keypoints and mesh vertices, and perform a similar optimization to solve for the parameters that best align these mesh vertices to the detected keypoints. You may also refer to this repo: https://github.com/nghorbani/moshpp

Thanks for the very quick response. Will take a look!

**Comment by SizheAn** [comment]
Hi,

When I read your code, I found that in https://github.com/CalciferZh/Minimal-IK/blob/72bfcbb768355fcc6706ca8cbdf50c3da25f9f63/models.py#L82, basically instead of specify the pose_pca, we can just specify the pose_abs. In another word, since my end goal is to get SMPL model parameters and render the human mesh, does that mean I only need to get pose_abs from my own keypoint and use that as the input to mesh.set_params function?

I can understand that the pose_abs, absolute model pose in axis-angle, shape [n_joints, 3]. I assume for each joint it is `[x*θ, y*θ, z*θ]`. How about the unit/scale of x, y, z? Is it in meters? Are there any example of the value of the pose_abs matrix? 

I think my next step will be writing a function to convert my 25x3 in-house human joint absolute coordinates to the 29x3(for smpl) axis-angle parameters. Do you think that's the correct direction? Thanks a lot!

**Comment by CalciferZh** [comment]
> How about the unit/scale of x, y, z? Are there any example of the value of the pose_abs matrix?

Axis-angle are angles, so the unit is radian. An example can be `np.tile(np.array([[np.pi/3, 0, 0]], [n_joints, 3]))` (but this is definitely not a valid pose.

> Do you think that's the correct direction?

It seems to be right if I understand you correctly.
