### ISSUE TITLE
Question on the shape of "keypoints"

### ISSUE THREAD

**Issue by zhangsanfeng86** [CalciferZh/Minimal-IK#14]
Hi @CalciferZh 
In spmlx , the shape of keypoint is (24,3), as follow:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/73547638/165430089-20122b43-6b99-4e80-a100-142121d0c6a6.png">

In  https://github.com/CalciferZh/Minimal-IK/blob/72bfcbb768355fcc6706ca8cbdf50c3da25f9f63/example.py#L47
the shape of keypoint is (29,3)

Could  padding (5,3) to solve this gap?

**Comment by CalciferZh** [comment]
Those are extended keypoints: https://github.com/CalciferZh/Minimal-IK/blob/master/armatures.py#L24

**Comment by zhangsanfeng86** [comment]
Thank you!!!

**Comment by aotaman** [comment]
hi,  zhangsanfeng86。我注意到你尝试使用Minimal-IK将bailando的3dkeypoint格式转化为smpl_trans和smpl_pose，你使用这种方法成功了吗？我在做同样的工作，我将example.py中keypiont改为bailando生成的3dkeypoint数据，得到的结果是很奇怪的，
