### ISSUE TITLE
Make SMPL from COCO Keypoints

### ISSUE THREAD

**Issue by aneeshbhattacharya** [CalciferZh/Minimal-IK#17]
Hi! I'm very new to this. I have coco keypoints of a person (18 keypoint format) for multiple frames. I would like to convert my keypoints to the SMPL format so that I can render some animations on Mixamo.
Is this at all possible? And if so, how can I do this?
My keypoint file is of the format [frames,joints,3] -> 300,18,3 (3 refers to positions along the x,y,z axis)

**Comment by Su-yukun** [comment]
> 你好！我对此很陌生。我有一个人的可可关键点（18 个关键点格式）用于多个帧。我想将我的关键点转换为 SMPL 格式，以便我可以在 Mixamo 上渲染一些动画。这可能吗？如果是这样，我该怎么做？我的关键点文件的格式为 [frames，joints，3] -> 300,18,3（3 是指沿 x，y，z 轴的位置）

Hi, have you tried to solve this problem of yours and how did it work out, if the problem was solved hope you can tell me how to do it as I am facing the same problem, thanks!

**Comment by aneeshbhattacharya** [comment]
Yes, you can check out this repository: https://github.com/google/aistplusplus_api
The file: https://github.com/google/aistplusplus_api/blob/2dd7b3e946b794fd0081c98e2e2433545abf8b87/processing/run_estimate_smpl.py#L64
This contains the code to estimate the SMPL parameters to match the keypoints in COCO and OpenPose.
