### ISSUE TITLE
想请教一下SMPL参数估计的正确食用方式（扶

### ISSUE THREAD

**Issue by syan2018** [CalciferZh/Minimal-IK#18]
首先感谢一下开源（跪）

我们试着从一批FBX动画文件中批量导出关键点信息转成SMPL格式，但在使用这个工具时遇到了点儿问题

![image](https://user-images.githubusercontent.com/24589615/210829876-e67790d0-2b6d-490a-93be-8c74279e8a0e.png)

左图是example中给出的随机关键点，右图是被我们用于求解的关键点，乍一看问题不大

根据比例估算了一下scale为2.7，以上述关键点为输入，微调了一下example里的代码求解（如下）

```python
def EstSMPLByKeypointAndScale(keypoints, scale):

    np.random.seed(20160923)

    pose_glb = np.zeros([1, 3]) # global rotation


    ########################## smpl settings ##########################
    # note that in smpl and smpl-h no pca for pose is provided
    # therefore in the model we fake an identity matrix as the pca coefficients
    # to make the code compatible

    n_pose = 23 * 3 # degrees of freedom, (n_joints - 1) * 3
    n_shape = 10
    pose_pca = np.random.uniform(-0.2, 0.2, size=n_pose)
    shape = np.random.normal(size=n_shape)
    mesh = KinematicModel(config.SMPL_MODEL_PATH, SMPLArmature, scale=scale)

    ########################## solving params ############################

    wrapper = KinematicPCAWrapper(mesh, n_pose=n_pose)
    solver = Solver(verbose=True)
  
    # 求解
    params_est = solver.solve(wrapper, keypoints)
  
    shape_est, pose_pca_est, pose_glb_est = wrapper.decode(params_est)

    print('----------------------------------------------------------------------')
    print('estimated parameters')
    print('pose pca coefficients:', pose_pca_est)
    print('pose global rotation:', pose_glb_est)
    print('shape: pca coefficients:', shape_est)

    mesh.set_params(pose_pca=pose_pca_est)
    mesh.save_obj('./est.obj')

    print('estimated meshes is saved into est.obj')
```

但是出来的估计结果mesh输出是这样的（不止一点邪典）

![image](https://user-images.githubusercontent.com/24589615/210831460-8a209f54-fa3b-4bd6-892b-f1ac7bee98ba.png)

方便请教一下出了这个结果可能是哪一步出了问题吗（泪下），是输入数据分布不太合适、对Scale的微调不足、还是求解代码写错了😭

**Comment by CalciferZh** [comment]
感谢你的兴趣  :)

抱歉我没有时间去仔细读你的代码，只能给出一些一般性的建议。（这个项目太久远了，具体的细节我也忘了）。

首先，这个库的鲁棒性可能是比较糟糕的，我从来没在外部数据上测试过它。它仅仅满足了我自己的项目需求，然后顺手开源了。

其次，根据关键点信息求SMPL参数是一个比较难解的优化问题（具体参考inverse kinematics）。
由于解空间的性质很差，加上约束条件很少，当初始化里目标姿态比较远的时候，这个工具是基本解不出来的。
它目前应该只能用作最后的微调。当姿态大体正确的时候，它可以进一步缩小误差。

如果要从任意姿态的关键点信息求解SMPL参数，就一定需要大改这个项目，主要是加一些约束项来避免你的例子里面的问题。
这个项目只能作为一份初始的框架来演示通过优化求解SMPL参数的大致流程与思路。

最后，可以考虑搜索一下近期的一些用神经网络求解这一问题的方法，或许会有一些可用的开源结果。

**Comment by syan2018** [comment]
非常感谢🤦‍♂️，我再研究看看能不能找到些别的好法子

**Comment by luoww1992** [comment]
@syan2018 
have you get a new method to get smpl pose by smpl  3d keypoints ?
can you share me ?

**Comment by syan2018** [comment]
> @syan2018 have you get a new method to get smpl pose by smpl 3d keypoints ? can you share me ?

maybe can try this repo [joints2smpl](https://github.com/wangsen1312/joints2smpl)

I also tried using MotionBuilder to retargeting the raw skeleton to SMPL fbx，then convert it to AMASS by this repo [Fbx2SMPL](https://github.com/syan2018/Fbx2SMPL)

**Comment by Lanjiong-Li** [comment]
@syan2018 hi, I am also working on turn custom dataset into SMPL parametric models. Can I discuss some technical details with you?

**Comment by syan2018** [comment]
> @syan2018 hi, I am also working on turn custom dataset into SMPL parametric models. Can I communicate with you?

of course！

**Comment by soddday** [comment]
@syan2018 你好，请问你了解相关的用3D关节点还原SMPLH参数的方法吗，我现在用自己的数据集73个关节点和对应484个参数的SMPLH模型，搭建了一个网络来拟合参数，可视化的结果能较好地还原人体的形态，但是手部细节有点糟糕，求教
