### ISSUE TITLE
Does the joint name order follows the official SMPL-H, SMPL?

### ISSUE THREAD

**Issue by wangzheallen** [CalciferZh/Minimal-IK#2]
For SMPL-H following https://github.com/vchoutas/smplx/blob/master/smplx/joint_names.py

for SMPL following line 18 to 42?
for SMPL-H following line 18 to 72?
for MANO following line 43 to 72?

**Comment by CalciferZh** [comment]
It's the same as the officially released version, but I don't remember the names exactly.

**Comment by wangzheallen** [comment]
Thanks!
