### ISSUE TITLE
Issues making this work with anything other than keypoints directly from mano mesh

### ISSUE THREAD

**Issue by pablovela5620** [CalciferZh/Minimal-IK#5]
I've been trying to get this IK solver to work with the FreiHand data but so far haven't been unable to. I wanted to see if there was something that I am doing wrong. Is there any sort of preprocessing needed to keypoints before being fed into the solver?

I have managed to get it working no problem when using the keypoints provided by the mesh

```python
_, keypoints = mesh.set_params(pose_pca=pose_pca, pose_glb=pose_glb, shape=shape)
```

and using the solver I get a really good result. But when using the XYZ keypoints from the FreiHand dataset I get the following
![image](https://user-images.githubusercontent.com/25287427/86293042-e1395500-bbbf-11ea-9c39-7f41ad8d6bc3.png)

I have done the following things. First I made sure that I had the joints in the correct order following the MANO convention rather than MPII that FreiHand is in. So 
```python 
class MANOHandJoints:
    n_joints = 21

    labels = [
        'W',  # 0
        'I0', 'I1', 'I2',  # 3
        'M0', 'M1', 'M2',  # 6
        'L0', 'L1', 'L2',  # 9
        'R0', 'R1', 'R2',  # 12
        'T0', 'T1', 'T2',  # 15
        'I3', 'M3', 'L3', 'R3', 'T3'  # 20, tips are manually added (not in MANO)
    ]
```

instead of this
```python 
class MPIIHandJoints:
    n_joints = 21

    labels = [
        'W',  # 0
        'T0', 'T1', 'T2', 'T3',  # 4
        'I0', 'I1', 'I2', 'I3',  # 8
        'M0', 'M1', 'M2', 'M3',  # 12
        'R0', 'R1', 'R2', 'R3',  # 16
        'L0', 'L1', 'L2', 'L3',  # 20
    ]
```
Secondly I made sure to scale the coordinates to be in millimeters rather than meters. Do I also need to mean center and normalize similar to how it's done in IKNet? I tried this as well but still was not getting good results. Any help would be greatly appreciated!

**Comment by CalciferZh** [comment]
Does the pose has a "global" rotation? If so, it's not surprising that this solver would fail.

**Comment by Elody-07** [comment]
I had the same issue using the HANDS19 pretrained model. I select a set of joints that seems not to have large global rotation but still failed. It just converge to large MSE errors. I tried official implementation from scipy.optimize and limit the params bound to [-1,1]. Then I can get reasonable pose but not fit to the input. Is this issue caused by the chosen of algorithm? Or simply the coordinate not aligning? 
Thank you for your project and looking forward to your answer~

**Comment by CalciferZh** [comment]
Hi, thanks for the interest. I would recommend to make sure that the scale and the step length are compatible. On the other hand, I'm not surprised if the code does not work well on "real" data, as it only optimizes on L2 distance without any regularization. You can add some customized regularization and prior terms to see if things can get better. Our intention to release the code was simply giving some "starter code" to implement a personalized IK solver.

**Comment by Elody-07** [comment]
> Hi, thanks for the interest. I would recommend to make sure that the scale and the step length are compatible. On the other hand, I'm not surprised if the code does not work well on "real" data, as it only optimizes on L2 distance without any regularization. You can add some customized regularization and prior terms to see if things can get better. Our intention to release the code was simply giving some "starter code" to implement a personalized IK solver.

Thank you very much!

**Comment by sidoodler** [comment]
@pablovela5620  Did you get a solution to your problem? I am facing the exact same problem - I don't understand what should be the coordinate system with respect to which the input key points need to be aligned. Please let me know if you got any lead! It would be greatly appreciated!!
Thanks a lot!
