### ISSUE TITLE
Is there any other solution ?

### ISSUE THREAD

**Issue by Z-Z-J** [CalciferZh/Minimal-IK#6]
SMPL parameters : 
            betas(10 x 1) + pose(24 x 3)  ------->   joint coordinates (and optional other keypoints)

your project:
             joint coordinates (and optional other keypoints)  -----> betas + pose

       I assume that the betas are fixed , only solve pose paramters。As it's only a "minimal" solution, is there any other solution?

**Comment by CalciferZh** [comment]
"Inverse kinematics" usually is merely about solving angles from positions. One the other hand, the shape parameters can be estimated according to bone lengths which can be derived from joint positions.

**Comment by Z-Z-J** [comment]
Thank you for your answer.  

The purpose of your project to given joint coordinates (and optional other keypoints),  solving  the corresponding model parameters.

So far , is there a better way to achieve the purpose?   Is anyone else  doing this job ?  If you know ,can you tell me? Thanks !!!

**Comment by CalciferZh** [comment]
I'm not quite sure about this. Good luck searching yourself :)
