### ISSUE TITLE
about dependices

### ISSUE THREAD

**Issue by MengHao666** [CalciferZh/Minimal-IK#7]
Hi, when I run example.py. I got errors as follows:

`Traceback (most recent call last):
  File "/home/haomeng/PycharmProjects/Minimal-IK/example.py", line 20, in <module>
    mesh = KinematicModel(config.MANO_MODEL_PATH, MANOArmature, scale=1000)
  File "/home/haomeng/PycharmProjects/Minimal-IK/models.py", line 23, in __init__
    params = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 2: ordinal not in range(128)`

It seems that code need to run in python2.X version but another dependices called open3d couldn't run in python2.X.

Could you export your virtual environment and provide the .yaml file.
Thanks!

**Comment by CalciferZh** [comment]
It's because the released SMPL model in under py2. I think you only need to modify the part that loads the model.

**Comment by MengHao666** [comment]
Got it, thanks!
