### ISSUE TITLE
Keypoint input format for MANO hand model

### ISSUE THREAD

**Issue by sidoodler** [CalciferZh/Minimal-IK#9]
Hi! After going through the code, I ain't able to understand the following:

If I want to find the **pose_abs** of the estimated hand using the MANO hand model, what should be the format in which I am required to input the hand key points? By that what I mean is, with respect to which coordinate system should I input the hand key points?

Thanks in advance!

**Comment by sidoodler** [comment]
It would be really helpful if someone could reply to this, as I am still stuck at this step. My project needs this crucial piece of information to move ahead. Any help will be much appreciated!!

**Comment by CalciferZh** [comment]
The unit is meter. The coordinate system does not matter because it only affects global rotation, and the method requires global notation to be known.
